name: ""
title: null

author:
  name: "Jan T. MÃ¼ller"
  email: "mail@jantmueller.com"

remote_theme: "jekyll/minima@4db5ffa"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { icon: github, url: "https://github.com/janthmueller"}
    - { icon: linkedin, url: "https://www.linkedin.com/in/jantmueller/"}
